### ISSUE TITLE
Differentiable McCormick relaxation generates NaN

### ISSUE THREAD

**Issue by ca0h** [PSORLab/McCormick.jl#42]
Differentiable McCormick relaxation (Diff) produces:
{2,Diff}(NaN, NaN, [NaN, NaN], [NaN, NaN], [NaN, NaN], true),
while Nonsmooth McCormick relaxation (NS) produces:
{2,NS}(-0.3612000000000003, -0.36120000000000035, [-0.361201, -0.3612], [-0.0, -0.0], [-0.0, -0.0], true)

McCormick.jl version: v0.10.1

MWE:
```
using McCormick

x = [1.2, 1.1]
p = [3.01, 1.01]

xI = [Interval(x[i]) for i=1:2]
pI = [Interval(p[i]) for i=1:2]

xMC = [MC{2, Diff}(xI[i]) for i=1:2]
pMC = [MC{2, Diff}(pI[i]) for i=1:2]

f(x,p) = p[1]*x[1]*(1.0 - x[2])

println(f(xMC,pMC))
```

**Comment by mewilhel** [comment]
So right now this behavior is enforced by:
```julia
@inline function mult_kernel(x1::MC{N,Diff}, x2::MC{N,Diff}, y::Interval{Float64}) where N
	degen1 = ((x1.Intv.hi - x1.Intv.lo) <= MC_DEGEN_TOL)
	degen2 = ((x2.Intv.hi - x2.Intv.lo) <= MC_DEGEN_TOL)
	(degen1 || degen2) && (return nan(MC{N,Diff}))
	return multiply_MV(x1, x2, y)
end
```

There were a few cases in which I got concave < convex relaxation for very small intervals due to rounding errors that occurred on very tight intervals (typically well-scaled problems weren't effected by this). I added the above check for tight intervals to resolve this. So there are a few ways to proceed here:

1. I can remove this check and `MC{N,Diff}` and the end user will need to make sure everything is fine. In this case, the user could potentially generate invalid relaxations without being aware.
2. I can remove this check and throw an error if concave < convex relaxation is encountered.
3. I can remove this check, treat Diff relaxations on small intervals as NS, and throw a one-time warning when this occurs. This would resolve the concave < convex issue without needing to throw an error (but we'd lose differentiability on the small domain).

I'm very much against option (1) as it introduces a silent error. I'd prefer options (2) or (3) but I'd like your input.

**Comment by ca0h** [comment]
Thanks for the prompt response. We think the second option is probably be the best.

**Comment by mewilhel** [comment]
Great. I think I'll leave in a more stringent degenerate interval check then treat the calculation as multiplying a number and a MC{N,Diff} or two numbers (if degenerate). Purposed solution below:

```julia
function check_relaxation_error!(x::MC{N,T}) where {N, T<:RelaxTag}
    if x.cc < x.cv
        @error "After performing calculations, a convex relaxation greater 
                than the associated concave relaxation was encountered. Please
                open an issue at https://github.com/PSORLab/McCormick.jl/issues/new
                so we may address this error in the future."
    end
    return nothing
end

@inline function mult_kernel(x1::MC{N,Diff}, x2::MC{N,Diff}, y::Interval{Float64}) where N
    degen1 = (x1.Intv.hi - x1.Intv.lo) == 0.0
    degen2 = (x2.Intv.hi - x2.Intv.lo) == 0.0
    if degen1 && !degen2
	out = x1.Intv.hi*x2
    elseif !degen1 && degen2
	out = x2.Intv.hi*x1
    elseif degen1 && degen2
	out = MC{N,Diff}(x1.Intv.hi*x2.Intv.hi)   # Needs to output a MC{N,Diff} for type stability
    else
    	out = multiply_MV(x1, x2, y)
	check_relaxation_error!(out)
    end
    return out
end
```

Outputs: 

```julia
MC{2,Diff}(-0.3612000000000003, -0.3612000000000003, [-0.361201, -0.3612], [0.0, 0.0], [0.0, 0.0], true)
```

Look good to you?

**Comment by ca0h** [comment]
Looks perfect to me. Thanks!

**Comment by mewilhel** [comment]
Cool cool!

I've uploaded this to the master and tagged a new release: https://github.com/PSORLab/McCormick.jl/commit/c6f716569d279be971f8f1f5c84b66a6a0e27c78.

So I'll close out this issue.
