### ISSUE TITLE
exp(x::MC) contains NaNs when x is degenerate

### ISSUE THREAD

**Issue by StevenChui88** [PSORLab/McCormick.jl#60]
I am a summer undergraduate research assistant working with Dr. Kamil Khan. We found that the concave relaxation of `exp(x::MC)` seems to be computed as `NaN` when x is degenerate. Presumably this is because of division by 0 in the secant formula in the concave relaxation of `exp`.

Example (using Julia v1.9.2 and McCormick.jl v0.13.4):

```julia
julia> using McCormick

julia> x = MC{1,NS}(2.0)
MC{1, NS}(2.0, 2.0, [2, 2], [0.0], [0.0], true)

julia> exp(x)
MC{1, NS}(7.38905609893065, NaN, [7.38905, 7.38906], [0.0], [NaN], true)

julia> exp(x).cc
NaN
```

**Comment by DimitriAlston** [comment]
Hey @StevenChui88. Apologies for the delayed response.

Thank you for pointing this out. We have made a change to the master branch that should address this issue.
Previously, McCormick checked the difference between the `exp` of the interval rather than the difference between the interval itself and this led to additional floating-point operations which essentially ignored the degeneracy.
We plan to look into the use outward-rounded intervals in the future as a more extensive change.

There are a few other changes we have planned before we tag another release, so keep an eye out.
